In [1]:
# Importing libraries
import networkx as nx
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter
from scipy.stats import pearsonr

**Disclaimer**: Some of the solutions shown today differ slightly from the official solutions in the book. For the *ground truth*, please always refer to the book’s solutions.

You are encouraged to:

- Try solving the exercises in your own way, different approaches are welcome.
- Use the documentation links we provide for the functions in our solutions.
- Treat the “hint” provided as the direct answer to that particular code cell.

# Chapter 8: Matrices

## Exercise 8.1:

Calculate the adjacency matrix, the stochastic adjacency matrix, and the graph Laplacian for this network (ex_8.1).

🔗 [NetworkX `read_edgelist` documentation](https://networkx.org/documentation/stable/reference/readwrite/generated/networkx.readwrite.edgelist.read_edgelist.html)

In [3]:
# Load the edgelist
G = nx.read_edgelist("ex_8.1.txt")
print(G)

Graph with 1133 nodes and 5451 edges


Depending on the version of your NetworkX, you can use either:

🔗 [NetworkX `to_numpy_array` documentation](https://networkx.org/documentation/stable/reference/generated/networkx.convert_matrix.to_numpy_array.html)
 
OR

🔗 [NetworkX `to_numpy_matrix` documentation](https://networkx.org/documentation/networkx-1.7/reference/generated/networkx.convert.to_numpy_matrix.html)

🔗 [NetworkX `to_scipy_sparse_matrix` documentation](https://networkx.org/documentation/networkx-1.11/reference/generated/networkx.convert_matrix.to_scipy_sparse_matrix.html)

<details>
<summary>💡 Hint</summary>

```python
adjmat = nx.to_numpy_array(G)
print(adjmat)

In [8]:
# Adjacency matrix
A = nx.to_numpy_array(G)
print(A.shape)


(1133, 1133)


🔗 [NumPy `sum` documentation](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sum.html)


<details>
<summary>💡 Hint</summary>

```python
adjmat_stoc = adjmat / adjmat.sum(axis=1)
print(adjmat_stoc)


In [9]:
# Stochastic adjacency
# If nx.to_numpy_matrix gives a memory error, try "to_scipy_sparse_matrix(G)", or nx.to_numpy_array(G)
stoch_adj = A / A.sum(axis = 1) # divide every entry in the Adj Matrix by the sum of entries for each column
# we select the columns using the axis = 1 parameter for .sum

🔗 [NetworkX `laplacian_matrix` documentation](https://networkx.org/documentation/stable/reference/generated/networkx.linalg.laplacianmatrix.laplacian_matrix.html)

<details>
<summary>💡 Hint</summary>

```python
laplacian = nx.laplacian_matrix(G)
print(laplacian.todense())


In [11]:
# Graph Laplacian
laplacian = nx.laplacian_matrix(G)
print(laplacian.todense())

[[30 -1 -1 ...  0  0  0]
 [-1 23 -1 ...  0  0  0]
 [-1 -1 38 ...  0  0  0]
 ...
 [ 0  0  0 ...  1  0  0]
 [ 0  0  0 ...  0  1  0]
 [ 0  0  0 ...  0  0  1]]


## Exercise 8.2:
Given this bipartite network (ex_8.2), calculate the stochastic adjacency matrix of its projection. Project along the axis of size 248. (Note: don’t ignore the weights).

🔗 [NetworkX `read_edgelist` documentation](https://networkx.org/documentation/stable/reference/readwrite/generated/networkx.readwrite.edgelist.read_edgelist.html)


In [5]:
# Load the data
G = nx.read_edgelist("ex_8.2.txt", data = [("weight", float),])
print(G)

Graph with 858 nodes and 1249 edges


🔗 [NetworkX `bipartite.sets` documentation](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.bipartite.basic.sets.html)

<details>
<summary>💡 Hint</summary>

```python
nodes = nx.algorithms.bipartite.basic.sets(G)


In [9]:
# Identify the two bipartite sets
set1, set2 = nx.algorithms.bipartite.basic.sets(G)

🔗 [NetworkX `biadjacency_matrix` documentation](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.bipartite.matrix.biadjacency_matrix.html#networkx.algorithms.bipartite.matrix.biadjacency_matrix)

<details>
<summary>💡 Hint</summary>

```python
adjmat = nx.algorithms.bipartite.matrix.biadjacency_matrix(G, nodes[0])


In [19]:
# Build the rectangular (non-square) biadjacency matrix for the bipartite graph
biadj_mat = nx.algorithms.bipartite.biadjacency_matrix(G, set1)
biadj_mat.todense()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

🔗 [Matrix multiplication (`dot`) in Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dot.html)

<details>
<summary>💡 Hint</summary>

```python
if adjmat.shape[0] == 248:
    adjmat_proj = adjmat.dot(adjmat.T)
else:
    adjmat_proj = adjmat.T.dot(adjmat)


In [15]:
# Project onto the smaller bipartite set axis (size = 248)
projected_biadjmat = biadj_mat.T.dot(biadj_mat)
projected_biadjmat.shape

(248, 248)

🔗 [NumPy `sum` documentation](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sum.html)

<details>
<summary>💡 Hint</summary>

```python
adjmat_proj_stoc = adjmat_proj / adjmat_proj.sum(axis=1)
print(adjmat_proj_stoc.todense())


In [17]:
# Convert projection into a stochastic adjacency matrix (normalize rows)
stoch_proj_biadj = projected_biadjmat / projected_biadjmat.sum(axis = 1)
stoch_proj_biadj.todense()

array([[0.01539366, 0.        , 0.        , ..., 0.00638352, 0.        ,
        0.        ],
       [0.        , 0.23661809, 0.        , ..., 0.        , 0.11265513,
        0.        ],
       [0.        , 0.        , 0.29511411, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.00085409, 0.        , 0.        , ..., 0.11605546, 0.        ,
        0.        ],
       [0.        , 0.05482614, 0.        , ..., 0.        , 0.24292234,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.03980389]])

## Exercise 8.3:
Calculate the eigenvalues and the right and left eigenvectors of the stochastic adjacency of this bipartite network (ex_8.3), using the same procedure applied in Exercise 8.2. 

Make sure to sort the eigenvalues in descending order (and sort the eigenvectors accordingly). Only take the real part of eigenvalues and eigenvectors, ignoring the imaginary part.

🔗 [NetworkX `read_edgelist` documentation](https://networkx.org/documentation/stable/reference/readwrite/generated/networkx.readwrite.edgelist.read_edgelist.html)  
🔗 [NetworkX `biadjacency_matrix` documentation](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.bipartite.matrix.biadjacency_matrix.html#networkx.algorithms.bipartite.matrix.biadjacency_matrix)

<details>
<summary>💡 Hint</summary>

```python
# Repeat projection and stochastic normalization steps from Exercise 8.2
G = nx.read_edgelist("ex_8.3.txt", data=[("weight", float),])
nodes = nx.algorithms.bipartite.basic.sets(G)
adjmat = nx.algorithms.bipartite.matrix.biadjacency_matrix(G, nodes[0])
if adjmat.shape[0] == 248:
    adjmat_proj = adjmat.dot(adjmat.T)
else:
    adjmat_proj = adjmat.T.dot(adjmat)
adjmat_proj_stoc = adjmat_proj / adjmat_proj.sum(axis=1)


In [29]:
# Repeat operations from Exercise 8.2 (using ex_8.3)
# Load bipartite network
G = nx.read_edgelist("ex_8.3.txt", data = [("weight", float),])
# Identify bipartite sets
set_1, set_2 = nx.algorithms.bipartite.sets(G)
# Biadjacency matrix
biadj_matrix = nx.algorithms.bipartite.biadjacency_matrix(G, set_1)
# Project onto smaller set
projected_biadjmatrix = biadj_matrix.T.dot(biadj_matrix)
# Stochastic adjacency matrix
stochastic_projected_biadjmatrix = projected_biadjmatrix / projected_biadjmatrix.sum(axis = 1)

🔗 [NumPy `np.linalg.eig` documentation](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html)  
🔗 [NumPy `np.real` documentation](https://numpy.org/doc/stable/reference/generated/numpy.real.html)  

<details>
<summary>💡 Hint</summary>

```python
# Convert to dense before computing eigenvectors
A_dense = adjmat_proj_stoc.toarray()
values, vectors_r = np.linalg.eig(A_dense)

# Only take real part and sort in descending order
values = np.real(values)
vectors_r = np.real(vectors_r)
sorted_index = values.argsort()[::-1]
values = values[sorted_index]
vectors_r = vectors_r[:, sorted_index]

In [35]:
# Convert sparse matrix to dense
dense_mat = stochastic_projected_biadjmatrix.todense()
# Eigenvalues and Eigenvectors.
values, vectors = np.linalg.eig(dense_mat)
values = np.real(values)
vectors = np.real(vectors)
# Compute right eigenvectors and eigenvalues
# Take only the real part of right eigenvalues and eigenvectors (ignore imaginary parts)
sorted_index = values.argsort()[::-1]
# Get the sorted indices of eigenvalues in descending order
# Why: since numpy returns them in random order, we need to sort the eigenvalues and eigenvectors
values, vectors = values[sorted_index], vectors[sorted_index]


array([  5, 247,   7,   6,   4,   3,   2,   1,   0,   8,   9,  10,  11,
        12,  15,  14,  13,  16,  17,  18,  20,  22,  23,  24,  25,  27,
        28,  26,  21,  19,  29,  30,  31,  32,  33,  37,  36,  35,  34,
        38,  40,  39,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
        51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  74,  73,  75,  76,
        79,  78,  77,  80,  81,  82,  83,  87,  88,  89,  90,  92,  91,
        86,  85,  84,  93,  94,  98, 101, 102, 100,  99,  97,  96, 103,
        95, 104, 105, 107, 106, 109, 108, 110, 111, 116, 117, 115, 120,
       119, 118, 114, 113, 112, 122, 124, 123, 121, 125, 126, 127, 129,
       130, 128, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
       142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 155,
       154, 157, 156, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
       169, 168, 170, 171, 172, 173, 174, 175, 176, 177, 178, 17

🔗 [NumPy `linalg.eig` documentation](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html)  

<details>
<summary>💡 Hint</summary>

```python
# Left eigenvectors are the right eigenvectors of the transpose
values, vectors_l = np.linalg.eig(A_dense.T)
values = np.real(values)
vectors_l = np.real(vectors_l)
sorted_index = values.argsort()[::-1]
values = values[sorted_index]
vectors_l = vectors_l[:, sorted_index]


In [ ]:
# Now left eigenvectors.
# Convert sparse matrix to dense for left eigenvectors
# Compute left eigenvectors by eig of the transpose
# Only take the real part
# Sort eigenvalues in descending order and reorder vectors accordingly
values_l, vectors_l = np.linalg.eig(dense_mat)
values_l = np.real(values_l)
vectors_l = np.real(vectors_l)
# Compute right eigenvectors and eigenvalues
# Take only the real part of right eigenvalues and eigenvectors (ignore imaginary parts)
sorted_index_l = values_l.argsort()[::-1]
# Get the sorted indices of eigenvalues in descending order
# Why: since numpy returns them in random order, we need to sort the eigenvalues and eigenvectors
values_l, vectors_l = values_l[sorted_index_l], vectors_l[sorted_index_l]

# Chapter 10: Paths and Walks

## Exercise 10.3:

What is the average reciprocity in the network (ex_10.3)? How many nodes have a reciprocity of zero?

🔗 [NetworkX `read_edgelist` documentation](https://networkx.org/documentation/stable/reference/readwrite/generated/networkx.readwrite.edgelist.read_edgelist.html)

In [36]:
# Load the data
G = nx.read_edgelist("ex_10.3.txt", create_using = nx.DiGraph())
print(G)

DiGraph with 2939 nodes and 30501 edges


The **reciprocity** of a directed graph is defined as the ratio of the number of edges pointing in both directions to the total number of edges in the graph.

**NOTE**: both functions can be used to calculate the same

🔗 [NetworkX `overall_reciprocity` documentation](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.reciprocity.overall_reciprocity.html#networkx.algorithms.reciprocity.overall_reciprocity)  

🔗 [NetworkX `reciprocity` documentation](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.reciprocity.reciprocity.html#networkx.algorithms.reciprocity.reciprocity) 


<details>
<summary>💡 Hint</summary>

```python
# Compute the overall reciprocity of the entire network
print(nx.overall_reciprocity(G))

# OR JUST
print(nx.reciprocity(G))

In [37]:
# Compute the overall reciprocity of the entire network
print(nx.reciprocity(G))

0.9720337038129897


🔗 [NetworkX `reciprocity` documentation](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.reciprocity.reciprocity.html#networkx.algorithms.reciprocity.reciprocity)  

<details>
<summary>💡 Hint</summary>

```python
# Compute reciprocity for each node individually
node_reciprocity = nx.reciprocity(G, nodes=list(G.nodes))
node_reciprocity


In [38]:
# Compute reciprocity for each node individually
individual_reciprocity = nx.reciprocity(G, nodes=list(G.nodes))
individual_reciprocity

{'1': 1.0,
 '2': 0.9523809523809523,
 '3': 0.8888888888888888,
 '4': 1.0,
 '5': 0.8571428571428571,
 '6': 1.0,
 '7': 0.6666666666666666,
 '8': 1.0,
 '9': 1.0,
 '10': 1.0,
 '11': 1.0,
 '12': 0.9707602339181286,
 '13': 0.9866666666666667,
 '14': 0.9955156950672646,
 '15': 0.9955555555555555,
 '16': 0.9900990099009901,
 '17': 0.9333333333333333,
 '18': 1.0,
 '19': 0.9361702127659575,
 '20': 1.0,
 '21': 1.0,
 '22': 0.8571428571428571,
 '23': 1.0,
 '24': 1.0,
 '25': 0.8571428571428571,
 '26': 0.6666666666666666,
 '27': 1.0,
 '28': 1.0,
 '29': 1.0,
 '30': 0.6666666666666666,
 '31': 1.0,
 '32': 1.0,
 '33': 0.6666666666666666,
 '34': 1.0,
 '35': 0.9411764705882353,
 '36': 0.9333333333333333,
 '37': 0.8888888888888888,
 '38': 1.0,
 '39': 1.0,
 '40': 1.0,
 '41': 0.9545454545454546,
 '42': 1.0,
 '43': 1.0,
 '44': 1.0,
 '45': 0.9912280701754386,
 '46': 0.875,
 '47': 1.0,
 '48': 1.0,
 '49': 1.0,
 '50': 1.0,
 '51': 0.9829059829059829,
 '52': 0.9928057553956835,
 '53': 0.9767441860465116,
 '54': 0.98

🔗 [Python `collections.Counter` documentation](https://docs.python.org/3/library/collections.html#collections.Counter)  

<details>
<summary>💡 Hint</summary>

```python
from collections import Counter

# Count how many nodes have zero reciprocity
zero_reciprocity = Counter(node_reciprocity.values())[0.0]
print("Nodes with zero reciprocity:", zero_reciprocity)

# Alternative way of doing it
count_zero_values = sum(1 for v in node_reciprocity.values() if v == 0)
print(f"Number of keys with value 0: {count_zero_values}")

In [42]:
# Count how many nodes have zero reciprocity
count = 0

for node in individual_reciprocity:
    if not individual_reciprocity[node]: count += 1
    
count

117

## Exercise 10.4:

How many weakly and strongly connected component does the network (ex_10.3) used in Exercise 10.3 have? Compare their sizes, in number of nodes, with the entire network. Which nodes are in these two components?

🔗 [NetworkX `read_edgelist` documentation](https://networkx.org/documentation/stable/reference/readwrite/generated/networkx.readwrite.edgelist.read_edgelist.html)

In [43]:
# Load the data
G = nx.read_edgelist("ex_10.3.txt", create_using = nx.DiGraph())
print(G)

DiGraph with 2939 nodes and 30501 edges


🔗 [NetworkX `weakly_connected_components` documentation](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.components.weakly_connected_components.html)  

<details>
<summary>💡 Hint</summary>

```python
# Compute all weakly connected components
wccs = list(nx.weakly_connected_components(G))

# Number of components
print("# Weakly connected components:", len(wccs))

# Largest component
wccs_largest = max(wccs, key=len)
print("Percentage of nodes in largest WCC: %1.2f%%" % (100 * len(wccs_largest) / len(G.nodes)))
print("Nodes in largest WCC: ", len(wccs_largest))

In [45]:
# Weak connectivity
wccs = list(nx.weakly_connected_components(G))
print(f'Weak CCs: {len(wccs)}')
# Compute all weakly connected components
print(f'Largest WCC: {len(max(wccs, key = len))}')
# Number of components
# Largest component


Weak CCs: 11
Largest WCC: 2905


🔗 [NetworkX `strongly_connected_components` documentation](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.components.strongly_connected_components.html)  

<details>
<summary>💡 Hint</summary>

```python
# Compute all strongly connected components
sccs = list(nx.strongly_connected_components(G))

# Number of components
print("# Strongly connected components:", len(sccs))

# Largest component
sccs_largest = max(sccs, key=len)
print("Percentage of nodes in largest SCC: %1.2f%%" % (100 * len(sccs_largest) / len(G.nodes)))
print("Nodes in largest SCC:", len(sccs_largest))

In [ ]:
# Strong connectivity

# Compute all strongly connected components

# Number of components

# Largest component


# Chapter 11: Random Walks

## Exercise 11.1:

Calculate the stationary distribution of this network (ex_11.1) in three ways: by raising the stochastic adjacency to a high power, by looking at the leading left eigenvector, and by normalizing the degree. Verify that they are all equivalent.

🔗 [NetworkX `read_edgelist` documentation](https://networkx.org/documentation/stable/reference/readwrite/generated/networkx.readwrite.edgelist.read_edgelist.html)

In [46]:
# Load the data
G = nx.read_edgelist("ex_11.1.txt")
print(G)

Graph with 1133 nodes and 5451 edges


🔗 [NetworkX `to_numpy_array` documentation](https://networkx.org/documentation/stable/reference/generated/networkx.convert_matrix.to_numpy_array.html)  
🔗 [NumPy broadcasting rules](https://numpy.org/doc/stable/user/basics.broadcasting.html)  

<details>
<summary>💡 Hint</summary>

```python
# Convert graph to adjacency matrix (as NumPy array, not matrix object)
A = nx.to_numpy_array(G)

# Make it stochastic (normalize rows)
A = A / A.sum(axis=1, keepdims=True)
print(A)


In [49]:
# Get the adjacency matrix
A = nx.to_numpy_array(G)
A = A / A.sum(axis = 1, keepdims=True)
# Convert graph to adjacency matrix (as NumPy array, not matrix object)
A
# Make it stochastic (normalize rows)


array([[0.        , 0.03333333, 0.03333333, ..., 0.        , 0.        ,
        0.        ],
       [0.04347826, 0.        , 0.04347826, ..., 0.        , 0.        ,
        0.        ],
       [0.02631579, 0.02631579, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

🔗 [NumPy `linalg.eig` documentation](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html)  
🔗 [NumPy `real` documentation](https://numpy.org/doc/stable/reference/generated/numpy.real.html) 

<details>
<summary>💡 Hint</summary>

```python
# Compute left eigenvectors, use A.T
values, vectors = np.linalg.eig(A.T)

# Sort eigenvalues and eigenvectors in descending order
sorted_index = values.argsort()[::-1]
values = np.real(values[sorted_index])
vectors = np.real(vectors[:, sorted_index])

# Leading left eigenvector = stationary distribution
stationary1 = vectors[:, 0]
stationary1 = stationary1 / stationary1.sum()
stationary1 = np.real(stationary1).flatten()
print(stationary1)


In [54]:
# METHOD 1: Eigenvectors & eigenvalues

# Compute left eigenvectors, use also A.T
values, vectors = np.linalg.eig(A.T)
# Sort eigenvalues and eigenvectors in descending order
values = np.real(values)
vectors = np.real(vectors)
sorted_index = values.argsort()[::-1]
values, vectors = values[sorted_index], vectors[sorted_index]
# Leading left eigenvector = stationary distribution
stationary1 = vectors[:,0]
stationary1 = stationary1 / stationary1.sum()
stationary1

array([0.00275179, 0.0021097 , 0.0034856 , ..., 0.0017428 , 0.00238488,
       0.00192625])

🔗 [NumPy `matrix_power` documentation](https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_power.html)  

<details>
<summary>💡 Hint</summary>

```python
# METHOD 2: Raise stochastic adjacency to a large power (e.g., 40)
A_power = np.linalg.matrix_power(A, 40)

# Any row now approximates stationary distribution
stationary2 = np.real(A_power[0, :])
stationary2 = stationary2 / stationary2.sum()
print(stationary2)

🔗 [NetworkX `Graph.degree` documentation](https://networkx.org/documentation/stable/reference/classes/generated/networkx.Graph.degree.html)  

<details>
<summary>💡 Hint</summary>

```python
# METHOD 3: Compute stationary distribution using normalized degree
stationary3 = np.array([G.degree(n) / (2 * len(G.edges)) for n in G.nodes])
print(stationary3)


In [ ]:
# METHOD 3: Compute stationary distribution using normalized degree


🔗 [NumPy `flatten` documentation](https://numpy.org/doc/2.3/reference/generated/numpy.ndarray.flatten.html)  
🔗 [SciPy `pearsonr` documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pearsonr.html)  

<details>
<summary>💡 Hint</summary>

```python
# Flatten all arrays to standardize shapes before correlation
s1 = np.array(stationary1).flatten()
s2 = np.array(stationary2).flatten()
s3 = np.array(stationary3).flatten()

# What's the correlation of these three vectors? 
print(pearsonr(s1, s2))
print(pearsonr(s2, s3))
print(pearsonr(s1, s3))


In [ ]:
# Flatten all arrays to standardize shapes before correlation, to avoid shape mismatch

# What's the correlation of these three vectors? 
